{
 "title": "Node_exporter",
 "time": { "from": "2019-04-25T14:51:12.132Z", "to": "2019-04-25T15:01:00.459Z" },
 "panels": [
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job:node_exporter:disk_usage" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job:node_exporter:cpu_usage" }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "job:node_exporter:ram_usage" }
   ]
  }
 ]
}